context:
  version: "0.1.4"

package:
  name: pixi-install-to-prefix
  version: ${{ version }}

source:
  url: https://github.com/pavelzw/pixi-install-to-prefix/archive/v${{ version }}.tar.gz
  sha256: 7d7a382fce6e892e9edada77a477b15a3b2a4165e9f7c4256d591d033645d640

build:
  number: 0
  script:
    env:
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_PROFILE_RELEASE_LTO: fat
    content:
      - if: linux
        then:
          - export OPENSSL_DIR=$PREFIX
      - if: unix
        then:
          - cargo auditable install --locked --no-track --bins --root ${{ PREFIX }} --path .
        else:
          - cargo auditable install --locked --no-track --bins --root %LIBRARY_PREFIX% --path .
      - cargo-bundle-licenses --format yaml --output ./THIRDPARTY.yml

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - cargo-auditable
  host:
    - if: linux
      then:
        - openssl

tests:
  - script:
      - pixi-install-to-prefix --help

about:
  homepage: https://github.com/pavelzw/pixi-install-to-prefix
  summary: Install pixi environments to an arbitrary prefix
  description: |
    Pixi installs your environments to `.pixi/envs/<env-name>` by default. If you want to install your environment to an arbitrary location on your system, you can use `pixi-install-to-prefix`.
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  repository: https://github.com/pavelzw/pixi-install-to-prefix

extra:
  recipe-maintainers:
    - pavelzw
    - ytausch
